Only allow @types/lodash less than 4.14.194 (PHNX-12420) (#28)
Motivation
---
When @types/lodash was upgraded to 4.14.194 errors in our CI tests started showing similar to this:

```
node_modules/@types/lodash/common/object.d.ts(1025,21): error TS1110: Type expected.
node_modules/@types/lodash/common/object.d.ts(1026,24): error TS1005: ':' expected.
node_modules/@types/lodash/common/object.d.ts(1026,38): error TS1005: ';' expected.
node_modules/@types/lodash/common/object.d.ts(1027,26): error TS1005: ':' expected.
```

Modification
---
Only allow @types/lodash less than 4.14.194

https://centeredge.atlassian.net/browse/PHNX-12420